### ISSUE TITLE
point annotation API

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-cocoa#16]
This should be direct as well as handling GeoJSON.

**Comment by mrtj** [comment]
Why this issue was closed? Is it implemented/won't be fixed/not of interest/duplicate?

**Comment by incanus** [comment]
Sorry, it is encapsulated by the broader work in https://github.com/mapbox/mapbox-gl-native/issues/507. Annotations in the style of MapKit will most assuredly be part of this library.

**Comment by mrtj** [comment]
Excellent news, thank you! This feature I wait the most that I could use this very promising library in my live apps!
