### ISSUE TITLE
Restore state after app backgrounding

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-cocoa#19]
When the app is backgrounded, we need to restore the state properly so that rendering will continue to work, e.g. like https://github.com/mapbox/llmr-native/commit/67ab9ff6f53712e37d169b86c197f633e52849bc, which destroys all framebuffer objects on backgrounding so that they are lazily recreated when we resume rendering.

Currently, the first frame that is rendered after the app is launched again is black. After that, drawing continues to work.

**Comment by incanus** [comment]
Not seeing this; reopen in `gl-native` if you do @kkaefer.
