### ISSUE TITLE
Add support for gl::isPackedDepthStencilSupported and gl::isDepth24Supported

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-cocoa#74]
@incanus After the merge of android-mason in mapboxgl-native you need to implement gl::isPackedDepthStencilSupported and gl::isDepth24Supported

Otherwise you will have a performance regression on iOS.

**Comment by incanus** [comment]
:point_right: https://github.com/mapbox/mapbox-gl-native/issues/839
