### ISSUE TITLE
Content insets

### ISSUE THREAD

**Issue by maciekish** [mapbox/mapbox-gl-cocoa#79]
Is proper support for content-insets planned? The map view should be able to be placed so that it fills the entire screen, below transparent nav-, tool- and status bars, but the compass rose and center coordinate etc should be calculated from what is actually visible and not behind a bar. The current MapBox for iOS has issues with this.

**Comment by incanus** [comment]
@maciekish Check out `-[MGLMapView viewControllerForLayoutGuides:]`, which takes care of this.
